project: "hooligan"
log_freq: 5

dataroot: '/usr/src/app/data'
image_size: 64
nc: 3
batch_size: 128
workers: 2
ngpu: 1
num_epochs: 2

generator:
  weigths: '/usr/src/app/src/models/weights/generator.pt' # path or null
  nz: 100
  ngf: 64
  optimizer:
    name: Adam
    Adam:
      lr: 0.0002
      beta1: 0.5

discriminator:
  weigths: '/usr/src/app/src/models/weights/discriminator.pt' # path or null
  ndf: 64
  optimizer:
    name: Adam
    Adam:
      lr: 0.0002
      beta1: 0.5

criterion: BCELoss
